server:
  port: 8073

spring:
  profiles: pre

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  #redis配置信息
  redis:
    database: 0
    host: 20.10.0.5
    password:  test@123
    port: 6379
    timeout: 5000
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0

  elasticsearch:
    rest:
      uris: 20.10.0.5:9200

logging:
  level:
    com:
      example:
        blogBigDataSystem:
          mapper : debug