server:
  port: 8070

#指定环境
spring:
  profiles:
    active: prod

  main:
    allow-bean-definition-overriding: true

  mail:
    host: smtp.163.com
    username: blog_data_system@163.com
    password: SBNEANQCRZRKXJWK
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

#配置日志
logging:
  config: classpath:logback-boot.xml